[package]
name = "waoo-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
waoo-common = { path = "../waoo-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "waoo"
path = "src/main.rs"
