name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: rustup toolchain install stable && rustup toolchain install nightly --component rust-src&& cargo install bpf-linker&& cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
